/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

 public class Problem2{
 	public static void main(String[] args){
 		System.out.format("Sum: %d", getSumEvenFibonacci(4000000));
 	}

 	public static long getSumEvenFibonacci(long maxAmountOfNumbers){
 		long sum = 0;
 		long prev0=1, prev1=2;
 		sum+=2;
 		while (prev1 < maxAmountOfNumbers){
 			long buffer = prev0;
	 		prev0 = prev1;
	 		prev1 = prev1 + buffer;
	 		if(prev1 > maxAmountOfNumbers){
 				break;
 			}
	 		//System.out.format("%d \n", prev1);
	 		if(prev1 % 2 == 0){
	 			sum+=prev1;
	 		}
 		}
 		return sum;
 	}
 }